version: '3.8'

services:
  rimovies-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: "${BUILD_DATE}"
        GIT_BRANCH: "${GIT_BRANCH}"
        GIT_COMMIT: "${GIT_COMMIT}"
    ports:
      - "8080:80"
    container_name: rimovies-app
